services:
  - type: web
    name: brightsteps
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn brightsteps_admin.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
