# Generated by Django 5.0.1 on 2026-07-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="homework_files/"),
        ),
    ]
