# Generated by Django 5.0.1 on 2026-07-09 03:23

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_student_teacher_classschedule_attendance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                storage=core.storage.SupabaseStorage(),
                upload_to="",
            ),
        ),
    ]
