# Generated by Django 6.0.7 on 2026-07-11 05:02

import core.storage
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_homework_attachment"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional title for the photo",
                        max_length=255,
                    ),
                ),
                (
                    "photo",
                    models.FileField(
                        storage=core.storage.SupabaseStorage(
                            bucket_name="events_photos"
                        ),
                        upload_to="",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Event Photos",
                "db_table": "event_photo",
            },
        ),
    ]
