# Generated by Django 6.0.7 on 2026-07-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_eventphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="parent_phone_number",
            field=models.CharField(
                blank=True,
                help_text="Used for parent login. Siblings can share the same number.",
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="grade_level",
            field=models.CharField(
                choices=[
                    ("Jr KG", "Jr KG"),
                    ("Sr KG", "Sr KG"),
                    ("Class 1", "Class 1"),
                    ("Class 2", "Class 2"),
                    ("Class 3", "Class 3"),
                    ("Class 4", "Class 4"),
                ],
                max_length=50,
            ),
        ),
    ]
