# Generated by Django 6.0.7 on 2026-07-16 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_student_parent_phone_number_alter_student_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_mr", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=50)),
                ("description_mr", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("color_hex", models.CharField(default="#3B82F6", max_length=7)),
            ],
            options={
                "db_table": "calendar_event",
            },
        ),
        migrations.CreateModel(
            name="SchoolNotice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_mr", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255)),
                ("content_mr", models.TextField()),
                ("content_en", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
                ("author_name", models.CharField(max_length=100)),
                ("is_urgent", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "school_notice",
            },
        ),
        migrations.AddField(
            model_name="student",
            name="average_quiz_score",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="badges",
            field=models.TextField(
                blank=True,
                help_text="Comma-separated list of badges, e.g. 'b1,b3'",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="lessons_completed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="quizzes_taken",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="student",
            name="total_stars",
            field=models.IntegerField(default=0),
        ),
    ]
