# Generated by Django 6.0.7 on 2026-07-18 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_calendarevent_schoolnotice_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("Marathi", "Marathi"),
                            ("English", "English"),
                            ("Mathematics", "Mathematics"),
                            ("Rhymes", "Rhymes"),
                            ("Stories", "Stories"),
                            ("Videos", "Videos"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title_mr", models.CharField(max_length=255)),
                ("title_en", models.CharField(max_length=255)),
                ("description_mr", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("content_mr", models.TextField(blank=True, null=True)),
                ("content_en", models.TextField(blank=True, null=True)),
                ("icon_res", models.CharField(blank=True, max_length=100, null=True)),
                ("color_hex", models.CharField(blank=True, max_length=7, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "lesson",
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("Marathi", "Marathi"),
                            ("English", "English"),
                            ("Mathematics", "Mathematics"),
                        ],
                        max_length=50,
                    ),
                ),
                ("question_mr", models.TextField()),
                ("question_en", models.TextField()),
                ("option_1_en", models.CharField(max_length=255)),
                ("option_2_en", models.CharField(max_length=255)),
                ("option_3_en", models.CharField(max_length=255)),
                ("option_4_en", models.CharField(max_length=255)),
                ("option_1_mr", models.CharField(max_length=255)),
                ("option_2_mr", models.CharField(max_length=255)),
                ("option_3_mr", models.CharField(max_length=255)),
                ("option_4_mr", models.CharField(max_length=255)),
                ("correct_answer_index", models.IntegerField()),
                ("points", models.IntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "quiz_question",
            },
        ),
    ]
