# Generated by Django 6.0.7 on 2026-07-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_lesson_quizquestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="grade_level",
            field=models.CharField(
                choices=[
                    ("Jr KG", "Jr KG"),
                    ("Sr KG", "Sr KG"),
                    ("Class 1", "Class 1"),
                    ("Class 2", "Class 2"),
                    ("Class 3", "Class 3"),
                    ("Class 4", "Class 4"),
                ],
                default="Class 1",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="grade_level",
            field=models.CharField(
                choices=[
                    ("Jr KG", "Jr KG"),
                    ("Sr KG", "Sr KG"),
                    ("Class 1", "Class 1"),
                    ("Class 2", "Class 2"),
                    ("Class 3", "Class 3"),
                    ("Class 4", "Class 4"),
                ],
                default="Class 1",
                max_length=50,
            ),
        ),
    ]
