# Generated by Django 5.0.1 on 2026-07-21 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_lesson_grade_level_quizquestion_grade_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="assigned_class",
            field=models.CharField(
                choices=[
                    ("Jr KG", "Jr KG"),
                    ("Sr KG", "Sr KG"),
                    ("Class 1", "Class 1"),
                    ("Class 2", "Class 2"),
                    ("Class 3", "Class 3"),
                    ("Class 4", "Class 4"),
                    ("All Classes", "All Classes"),
                ],
                default="Class 1",
                max_length=50,
            ),
        ),
    ]
